services:
  # 1. MySQL 데이터베이스
  db:
    image: mysql:8.0
    container_name: nosmoke-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  # 2. Spring Boot Backend
  backend:
    build: ./backend
    container_name: nosmoke-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"

  # 3. Nginx (Gateway)
  nginx:
    image: nginx:latest
    container_name: nosmoke-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend

  # 4. Jenkins
  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: nosmoke-jenkins
    user: root
    ports:
      - "9000:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Seoul

  # 5. Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: nosmoke-prometheus
    ports:
      - "9091:9090" # 호스트 포트 9091로 변경(Jenkins:9090)
    volumes:
      # 설정파일 연결
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      # 데이터 영속성(컨테이너가 꺼져도 수집한 데이터 보존)
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: nosmoke-grafana
    ports:
      - "3000:3000"
    volumes:
      # 대시보드 설정, 계정 정보 영속성
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus


# 볼륨 정의(도커가 관리하는 저장소)
volumes:
  db_data:
  prometheus_data:
  grafana_data: